### ISSUE TITLE
Evaluating a whitespace-only file (or string) segfaults.

### ISSUE THREAD

**Issue by ColinGilbert** [ChaiScript/ChaiScript#193]
EDIT: I found that a commented-out .chai file crashes as reliably as a whitespace-only one. The title of this bug report has been changed to reflect this information.

Note: A file with uncommented gibberish throws an exception, as is expected. Also, compiling with or without threading makes no difference. Furthermore, the eval() method with the same file slurped into a string also segfaults for the same input.

Note: 

Debugging info:

Here is the gdb output when using chai.eval_file() with a whitespace-only file.

```
(gdb) run
Starting program: /home/noob/noobgame/sandbox/e 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffecf08700 (LWP 31212)]
[New Thread 0x7fffd7f30700 (LWP 31213)]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000b6d0ea in std::__shared_ptr<chaiscript::AST_Node, (__gnu_cxx::_Lock_policy)2>::operator-> (this=0x0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/include/g++-v4/bits/shared_ptr_base.h:1048
1048		return _M_ptr;
(gdb) 
```

Here is the backtrace.
```
(gdb) bt
#0  0x0000000000b6d0ea in std::__shared_ptr<chaiscript::AST_Node, (__gnu_cxx::_Lock_policy)2>::operator-> (this=0x0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/include/g++-v4/bits/shared_ptr_base.h:1048
#1  0x0000000000c11b84 in chaiscript::eval::File_AST_Node::eval_internal (this=0x1c3ab30, 
    t_ss=...)
    at /home/noob/noobgame/engine/lib/chaiscript/include/chaiscript/language/chaiscript_eval.hpp:1128
#2  0x0000000000b6c4b7 in chaiscript::AST_Node::eval (this=0x1c3ab30, t_e=...)
    at /home/noob/noobgame/engine/lib/chaiscript/include/chaiscript/language/chaiscript_common.hpp:482
#3  0x0000000000c252a6 in chaiscript::ChaiScript::do_eval (this=0x1727468, t_input="\n", 
    t_filename="./script.chai")
    at /home/noob/noobgame/engine/lib/chaiscript/include/chaiscript/language/chaiscript_engine.hpp:275
#4  0x0000000000c29139 in chaiscript::ChaiScript::eval_file (this=0x1727468, 
    t_filename="./script.chai", t_handler=std::shared_ptr (empty) 0x0)
    at /home/noob/noobgame/engine/lib/chaiscript/include/chaiscript/language/chaiscript_engine.hpp:902
#5  0x0000000000bf49a5 in noob::application::update (this=0x1727200, 
    delta=0.016689194366335869) at /home/noob/noobgame/engine/common/Application.cpp:204
#6  0x0000000000bf507a in noob::application::step (this=0x1727200)
    at /home/noob/noobgame/engine/common/Application.cpp:262
#7  0x0000000000b6a28e in main ()
    at /home/noob/noobgame/engine/platform/nix/EngineDesktop.cpp:119
(gdb) 
```
Here is a full backtrace:
```
(gdb) bt full
#0  0x0000000000b6d0ea in std::__shared_ptr<chaiscript::AST_Node, (__gnu_cxx::_Lock_policy)2>::operator-> (this=0x0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/include/g++-v4/bits/shared_ptr_base.h:1048
No locals.
#1  0x0000000000c11b84 in chaiscript::eval::File_AST_Node::eval_internal (this=0x1c3ab30, 
    t_ss=...)
    at /home/noob/noobgame/engine/lib/chaiscript/include/chaiscript/language/chaiscript_eval.hpp:1128
        i = 0
        num_children = 0
#2  0x0000000000b6c4b7 in chaiscript::AST_Node::eval (this=0x1c3ab30, t_e=...)
    at /home/noob/noobgame/engine/lib/chaiscript/include/chaiscript/language/chaiscript_common.hpp:482
No locals.
#3  0x0000000000c252a6 in chaiscript::ChaiScript::do_eval (this=0x1727468, t_input="\n", 
    t_filename="./script.chai")
    at /home/noob/noobgame/engine/lib/chaiscript/include/chaiscript/language/chaiscript_engine.hpp:275
        parser = {m_input_pos = 0 '\000', m_input_end = 0 '\000', m_line = 2, m_col = 1, 
          m_multiline_comment_begin = "/*", m_multiline_comment_end = "*/", 
          m_singleline_comment = "//", m_filename = warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<std::string, std::allocator<std::string>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<std::string, std::allocator<std::string>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr (count 2, weak 0) 0x17aae20, 
          m_match_stack = std::vector of length 1, capacity 2 = {
            std::shared_ptr (count 2, weak 1) 0x1c3ab30}, m_alphabet = {{
              false <repeats 38 times>, true, false, false, false, true, true, false, true, 
              true, true, false <repeats 12 times>, true, true, true, true, 
              false <repeats 30 times>, true, false <repeats 29 times>, true, 
              false <repeats 131 times>}, {false <repeats 48 times>, true, true, true, true, 
              true, true, true, true, true, true, false, false, false, false, false, false, 
              false, true <repeats 26 times>, false, false, false, false, true, false, 
              true <repeats 26 times>, false <repeats 133 times>}, {
              false <repeats 48 times>, true, true, true, true, true, true, true, true, 
              true, true, false <repeats 198 times>}, {false <repeats 46 times>, true, 
              false, true, true, true, true, true, true, true, true, true, true, 
              false <repeats 198 times>}, {false <repeats 88 times>, true, 
              false <repeats 31 times>, true, false <repeats 135 times>}, {
              false <repeats 48 times>, true, true, true, true, true, true, true, true, 
              true, true, false, false, false, false, false, false, false, true, true, true, 
              true, true, true, false <repeats 26 times>, true, true, true, true, true, 
              true, false <repeats 153 times>}, {false <repeats 66 times>, true, 
              false <repeats 31 times>, true, false <repeats 157 times>}, {
              false <repeats 48 times>, true, true, false <repeats 206 times>}, {
              false <repeats 65 times>, true <repeats 26 times>, false, false, false, false, 
              true, false, true <repeats 26 times>, false <repeats 133 times>}, {false, 
              false, false, false, false, false, false, false, false, true, 
              false <repeats 22 times>, true, false <repeats 223 times>}, {
              false <repeats 76 times>, true, false, false, false, false, false, false, 
              false, false, true, false <repeats 22 times>, true, false, false, false, 
              false, false, false, false, false, true, false <repeats 138 times>}, {
              false <repeats 70 times>, true, false, false, false, false, false, true, 
              false <repeats 25 times>, true, false, false, false, false, false, true, 
              false <repeats 147 times>}}, 
          m_operator_matches = std::vector of length 11, capacity 16 = {
            std::vector of length 1, capacity 1 = {"?"}, 
            std::vector of length 1, capacity 1 = {"||"}, 
            std::vector of length 1, capacity 1 = {"&&"}, 
            std::vector of length 1, capacity 1 = {"|"}, 
---Type <return> to continue, or q <return> to quit---
            std::vector of length 1, capacity 1 = {"^"}, 
            std::vector of length 1, capacity 1 = {"&"}, 
            std::vector of length 2, capacity 2 = {"==", "!="}, 
            std::vector of length 4, capacity 4 = {"<", "<=", ">", ">="}, 
            std::vector of length 2, capacity 2 = {"<<", ">>"}, 
            std::vector of length 2, capacity 2 = {"+", "-"}, 
            std::vector of length 3, capacity 3 = {"*", "/", "%"}}, 
          m_operators = std::vector of length 11, capacity 16 = {
            chaiscript::AST_Node_Type::Ternary_Cond, chaiscript::AST_Node_Type::Logical_Or, 
            chaiscript::AST_Node_Type::Logical_And, chaiscript::AST_Node_Type::Bitwise_Or, 
            chaiscript::AST_Node_Type::Bitwise_Xor, chaiscript::AST_Node_Type::Bitwise_And, 
            chaiscript::AST_Node_Type::Equality, chaiscript::AST_Node_Type::Comparison, 
            chaiscript::AST_Node_Type::Shift, chaiscript::AST_Node_Type::Addition, 
            chaiscript::AST_Node_Type::Multiplication}}
#4  0x0000000000c29139 in chaiscript::ChaiScript::eval_file (this=0x1727468, 
    t_filename="./script.chai", t_handler=std::shared_ptr (empty) 0x0)
    at /home/noob/noobgame/engine/lib/chaiscript/include/chaiscript/language/chaiscript_engine.hpp:902
No locals.
#5  0x0000000000bf49a5 in noob::application::update (this=0x1727200, 
    delta=0.016689194366335869) at /home/noob/noobgame/engine/common/Application.cpp:204
        p = {static preferred_separator = 47 '/', m_pathname = "./script.chai"}
        ec = {m_val = 0, 
          m_cat = 0x145fe70 <boost::system::system_category()::system_category_const>}
        last_write = 0
        t = 1436726562
        time_elapsed = 0.25968920324521605
#6  0x0000000000bf507a in noob::application::step (this=0x1727200)
    at /home/noob/noobgame/engine/common/Application.cpp:262
        timeNow = {tv_sec = 126507, tv_nsec = 558571565}
        uNowNano = 126507558571565
        delta = 0.016689194366335869
#7  0x0000000000b6a28e in main ()
    at /home/noob/noobgame/engine/platform/nix/EngineDesktop.cpp:119
        info = {movement = false, translation = {v = {_M_elems = {0, 0, 0}}}, rotation = {
            v = {_M_elems = {0, 0, 0}}}}
        window = 0x1569460
(gdb) 
```

Here is the code I used:

https://github.com/ColinGilbert/noobwerkz-engine/blob/master/engine/common/Application.cpp

Code responsible is in application::update().

I hope this is of use; if there is anything else I can do, please let me know.

**Comment by ColinGilbert** [comment]
Also of note is that compiling with or without threading makes no difference, and that the eval() method dalso segfaults for the same input.

**Comment by lefticus** [comment]
Thank you for the report. I've been tracking a handful of crashes that have been discovered using http://lcamtuf.coredump.cx/afl/

I'll make sure this gets added to the list to correct. I hope to start digging into this in the next few days.
