### ISSUE TITLE
Homebrew test block fails with 6.0.0 but passes with 5.8.6

### ISSUE THREAD

**Issue by ilovezfs** [ChaiScript/ChaiScript#328]
* Compiler Used: clang-800.0.42.1 (Xcode 8)
 * Operating System: macOS 10.11
 * Architecture (ARM/x86/32bit/64bit/etc): x86_64
 

### Expected Behavior 
Expect test block to pass as it did with 5.8.6.

### Actual Behavior
Test block fails.

### Minimal Example to Reproduce Behavior
```
  test do
    (testpath/"test.cpp").write <<-EOS.undent
      #include <chaiscript/chaiscript.hpp>
      #include <chaiscript/chaiscript_stdlib.hpp>
      #include <cassert>
      int main() {
        chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());
        assert(chai.eval<int>("123") == 123);
      }
    EOS

    system ENV.cxx, "test.cpp", "-L#{lib}", "-std=c++11", "-o", "test"
    system "./test"
  end
```

Output:
```
iMac-TMP:homebrew-core joe$ brew test chaiscript -dv
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chaiscript.rb
Testing chaiscript
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170222-8880-co04ix.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chaiscript.rb -dv
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chaiscript.rb
==> /usr/bin/clang++ test.cpp -L/usr/local/Cellar/chaiscript/6.0.0/lib -std=c++11 -o test
In file included from test.cpp:1:
In file included from /usr/local/include/chaiscript/chaiscript.hpp:823:
In file included from /usr/local/include/chaiscript/chaiscript_basic.hpp:12:
In file included from /usr/local/include/chaiscript/dispatchkit/dispatchkit.hpp:29:
In file included from /usr/local/include/chaiscript/dispatchkit/boxed_cast.hpp:16:
In file included from /usr/local/include/chaiscript/dispatchkit/boxed_cast_helper.hpp:17:
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:84:16: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
        static auto get(Boxed_Value::Void_Type, bool t_return_value)
               ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:96:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
          static auto get(const std::shared_ptr<T> *obj, bool t_return_value)
                 ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:102:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
          static auto get(const std::shared_ptr<T> &obj, bool t_return_value)
                 ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:114:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
          static auto get(std::shared_ptr<T> &&obj, bool t_return_value)
                 ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:129:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
          static auto get(T *t, bool t_return_value)
                 ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:135:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
          static auto get(const T *t, bool t_return_value)
                 ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:142:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
          static auto get(std::reference_wrapper<T> obj, bool t_return_value)
                 ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:155:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
          static auto get(std::unique_ptr<T> &&obj, bool t_return_value)
                 ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:168:18: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
          static auto get(T t, bool t_return_value)
                 ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:247:7: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
      auto pointer_sentinel(std::shared_ptr<T> &ptr) const
      ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:61:28: error: no member named 'make_unique' in namespace 'std'
            m_attrs = std::make_unique<std::map<std::string, std::shared_ptr<Data>>>(*rhs.m_attrs);
                      ~~~~~^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:61:84: error: expected '(' for function-style cast or type construction
            m_attrs = std::make_unique<std::map<std::string, std::shared_ptr<Data>>>(*rhs.m_attrs);
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:86:18: error: no viable conversion from returned value of type 'typename enable_if<!is_array<Data>::value, shared_ptr<Data> >::type' (aka 'std::__1::shared_ptr<chaiscript::Boxed_Value::Data>') to function return type 'int'
          return std::make_shared<Data>(
                 ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:325:34: error: no member named 'make_unique' in namespace 'std'
          m_data->m_attrs = std::make_unique<std::map<std::string, std::shared_ptr<Data>>>();
                            ~~~~~^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:325:90: error: expected '(' for function-style cast or type construction
          m_data->m_attrs = std::make_unique<std::map<std::string, std::shared_ptr<Data>>>();
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:325:92: error: expected expression
          m_data->m_attrs = std::make_unique<std::map<std::string, std::shared_ptr<Data>>>();
                                                                                           ^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:342:34: error: no member named 'make_unique' in namespace 'std'
          m_data->m_attrs = std::make_unique<std::map<std::string, std::shared_ptr<Data>>>(*t_obj.m_data->m_attrs);
                            ~~~~~^
/usr/local/include/chaiscript/dispatchkit/boxed_value.hpp:342:90: error: expected '(' for function-style cast or type construction
          m_data->m_attrs = std::make_unique<std::map<std::string, std::shared_ptr<Data>>>(*t_obj.m_data->m_attrs);
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from test.cpp:1:
In file included from /usr/local/include/chaiscript/chaiscript.hpp:823:
In file included from /usr/local/include/chaiscript/chaiscript_basic.hpp:12:
In file included from /usr/local/include/chaiscript/dispatchkit/dispatchkit.hpp:29:
In file included from /usr/local/include/chaiscript/dispatchkit/boxed_cast.hpp:16:
/usr/local/include/chaiscript/dispatchkit/boxed_cast_helper.hpp:190:16: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
        static auto cast(const Boxed_Value &ob, const Type_Conversions_State *)
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /usr/bin/clang++ test.cpp -L/usr/local/Cellar/chaiscript/6.0.0/lib -std=c++11 -o test
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

**Comment by lefticus** [comment]
It's just as it says - the homebrew script needs to be updated to pass `-std=c++14` to the compiler, but I don't know who hosts the homebrew scripts or how to update them.

**Comment by ilovezfs** [comment]
I'm one of the maintainers, so don't worry about that part.

Unfortunately, it still fails in that case. That was the first thing I tried.

```
iMac-TMP:~ joe$ brew test chaiscript -vd
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chaiscript.rb
Testing chaiscript
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170223-53261-lfrwbx.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chaiscript.rb -vd
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/chaiscript.rb
==> /usr/bin/clang++ test.cpp -L/usr/local/Cellar/chaiscript/6.0.0/lib -std=c++14 -o test
test.cpp:5:26: error: no matching constructor for initialization of 'chaiscript::ChaiScript'
  chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());
                         ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/chaiscript/chaiscript.hpp:830:9: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'ModulePtr' (aka 'shared_ptr<chaiscript::Module>') to 'const chaiscript::ChaiScript' for 1st argument
  class ChaiScript : public ChaiScript_Basic
        ^
/usr/local/include/chaiscript/chaiscript.hpp:833:7: note: candidate constructor not viable: no known conversion from 'ModulePtr' (aka 'shared_ptr<chaiscript::Module>') to 'std::vector<std::string>' (aka 'vector<basic_string<char, char_traits<char>, allocator<char> > >') for 1st argument
      ChaiScript(std::vector<std::string> t_modulepaths = {},
      ^
test.cpp:6:23: error: expected '(' for function-style cast or type construction
  assert(chai.eval<int>("123") == 123);
                   ~~~^
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
2 errors generated.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /usr/bin/clang++ test.cpp -L/usr/local/Cellar/chaiscript/6.0.0/lib -std=c++14 -o test
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 
```

**Comment by lefticus** [comment]
That `test.cpp` is no longer valid with the new constructors. You should be able to get it working by changing that to 

```
chaiscript::ChaiScript chai;
```

-Jason

**Comment by ilovezfs** [comment]
@lefticus thanks that seems to fix it. You may want to update the readme accordingly: https://github.com/ChaiScript/ChaiScript/blame/develop/readme.md#L124

Also, do you have an example that actually links to one of the libraries in `lib/chaiscript`?

The example above doesn't seem to produce a binary linked to libchaiscript_stdlib-6.0.0.so, libstl_extra.so, or libtest_module.so.

Also is it intentional that those end in .so not .dylib?

**Comment by ilovezfs** [comment]
Specifically the linkage for the binary produced by the current example is
```
bash-3.2$ otool -L test
test:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by lefticus** [comment]
Those three libs are all things that might be dynamically loaded, so everything is operating as expected.

**Comment by ilovezfs** [comment]
It's not clear to me how to check whether it will actually be able to find them. If I rm -rf the lib directory it still passes, and they don't seem to be referenced at all within the executable.
