### ISSUE TITLE
iterator with for( : ) causes crash (Chaiscript 6.0.0)

### ISSUE THREAD

**Issue by olikraus** [ChaiScript/ChaiScript#392]
* Compiler Used: gcc 6.3.0
 * Operating System: Win8, MinGW, Chaiscript 6.0.0
 * Architecture (ARM/x86/32bit/64bit/etc): Intel
 

### Expected Behavior 
Return a vector with all keys of a map.
In 5.x the following function works without problem:
```
def keys(map) 
{ 
  auto range := range(map);         // get a range obj from the map
  auto v := Vector();                // create empty vector
  while (!range.empty())             // as long as the range has elements
  {         
    v.push_back(range.front().first());    // append key to the vector
    range.pop_front();             // remove first element from the range
  }
  v;                              // return the new vector
} 
print(keys(["1a":111, "2b":222]));
```
In 6.x.x I wanted to use the new for loop:
```
def keys(map) 
{ 
  auto v := Vector();                // create empty vector
  auto i;
  for( i : map )
  {
    v.push_back(i.first());    // append key to the vector
  }
  v;                              // return the new vector
} 
print(keys(["1a":111, "2b":222]));
```

### Actual Behavior 
The version with for( : ) for 6.x.x crashes without exception.

### Minimal Example to Reproduce Behavior
```
def keys(map) 
{ 
  auto v := Vector();                // create empty vector
  auto i;
  for( i : map )
  {
    v.push_back(i.first());    // append key to the vector
  }
  v;                              // return the new vector
} 
print(keys(["1a":111, "2b":222]));
```

### Workaround
It looks like, that there is a memory issue. Cloning i.first() will solve the problem:
```
def keys(map) 
{ 
  auto v := Vector();                // create empty vector
  auto i;
  for( i : map )
  {
    v.push_back(clone(i.first()));    // append key to the vector
  }
  v;                              // return the new vector
} 
print(keys(["1a":111, "2b":222]));
```

**Comment by olikraus** [comment]
Not sure whether this helps, but here the stack frame output of gdb:

```
Program received signal SIGSEGV, Segmentation fault.
0x76679b60 in msvcrt!memcpy () from C:\Windows\syswow64\msvcrt.dll
(gdb) up
#1  0x00403032 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.732] ()
(gdb) up
#2  0x0049a16f in chaiscript::dispatch::Proxy_Function_Callable_Impl<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), chaiscript::bootstrap::Bootstrap::bootstrap(chaiscript::Module&)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#2}>::do_call(std::vector<chaiscript::Boxed_Value, std::allocator<std::vector> > const&, chaiscript::Type_Conversions_State const&) const ()
(gdb) up
#3  0x00494fa5 in chaiscript::dispatch::Proxy_Function_Base::operator()(std::vector<chaiscript::Boxed_Value, std::allocator<chaiscript::Boxed_Value> > const&, chaiscript::Type_Conversions_State const&) const ()
(gdb) up
#4  0x0045a366 in chaiscript::Boxed_Value chaiscript::dispatch::dispatch<std::vector<std::shared_ptr<chaiscript::dispatch::Proxy_Function_Base>, std::allocator<std::shared_ptr<chaiscript::dispatch::Proxy_Function_Base> > > >(std::vector<std::shared_ptr<chaiscript::dispatch::Proxy_Function_Base>, std::allocator<std::shared_ptr<chaiscript::dispatch::Proxy_Function_Base> > > const&, std::vector<chaiscript::Boxed_Value, std::allocator<chaiscript::Boxed_Value> > const&, chaiscript::Type_Conversions_State const&) ()
```
